name: st10047613

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  MAIN_MODULE: app
  APP_NAME: ActionsExampleG2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set date
      - name: Set build date
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set repository name
      - name: Set repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      # Setup Java
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      # Grant execute permission for Gradle
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Run Tests
      - name: Run unit tests
        run: ./gradlew test --no-daemon

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew ${{ env.MAIN_MODULE }}:assembleDebug --no-daemon

      # Build Release APK
      - name: Build Release APK
        run: ./gradlew ${{ env.MAIN_MODULE }}:assembleRelease --no-daemon

      # Build Release AAB
      - name: Build Release Bundle (AAB)
        run: ./gradlew ${{ env.MAIN_MODULE }}:bundleRelease --no-daemon

      # Upload Debug APK
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_DATE }}-${{ env.APP_NAME }}-${{ env.REPO_NAME }}-debug-apk
          path: ${{ env.MAIN_MODULE }}/build/outputs/apk/debug/*.apk

      # Upload Release APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_DATE }}-${{ env.APP_NAME }}-${{ env.REPO_NAME }}-release-apk
          path: ${{ env.MAIN_MODULE }}/build/outputs/apk/release/*.apk

      # Upload AAB
      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_DATE }}-${{ env.APP_NAME }}-${{ env.REPO_NAME }}-release-aab
          path: ${{ env.MAIN_MODULE }}/build/outputs/bundle/release/*.aab
